version: "3.8"

services:
    db:
        image: postgres:14
        container_name: ml_project_db
        environment:
            - POSTGRES_DB=ml_project
            - POSTGRES_USER=ml_user
            - POSTGRES_PASSWORD=ml_password
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ml_user -d ml_project"]
            interval: 10s
            timeout: 5s
            retries: 5

    app:
        build: .
        container_name: ml_project_app
        environment:
            - DB_HOST=db
            - DB_NAME=ml_project
            - DB_USER=ml_user
            - DB_PASSWORD=ml_password
            - DB_PORT=5432
        ports:
            - "8501:8501"
        volumes:
            - ./datasets:/app/datasets
            - ./models:/app/models
        depends_on:
            db:
                condition: service_healthy

volumes:
    postgres_data:
