version: "3.8"

services:
    app:
        build: .
        container_name: ml_project_app
        ports:
            - "8501:8501"
        volumes:
            - ./datasets:/app/datasets
            - ./models:/app/models
            - ./ml_project.db:/app/ml_project.db
        environment:
            - STREAMLIT_SERVER_PORT=8501
            - STREAMLIT_SERVER_ADDRESS=0.0.0.0

volumes:
    postgres_data:
